language: ruby
script: "script/test_all"
sudo: false
email: false
before_install:
  - gem update --system # update rubygems
  - gem update bundler
bundler_args: "--standalone --binstubs --without documentation"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - ruby-head
  - ree
  - jruby-9.1.7.0
  - jruby-head
  - jruby-1.7
  - rbx-3
env:
  - JRUBY_OPTS='--dev'
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
